/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenciadeautos;

/**
 *
 * @author info7
 */


import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListModel;


public class FrameInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrameInicio
     * 
     * 
     */      

    DefaultListModel listaModelo = new DefaultListModel();
    List<Auto> lista = new ArrayList<>();
    
 
  public void setLista(List lista){
  this.lista = lista;
  }
                       
  public void cargarLista(){
                    
    for( int i = 0 ; i < lista.size(); i++){
    listaModelo.addElement(lista.get(i).toString());
    listaPrincipal.setModel(listaModelo);
    
                    }            
                }
    
    
    
    
    
    
    
    
    public FrameInicio() {
        initComponents();
        

        txtCantidadPasajeros.setEnabled(true);
        txtCapacidadCarga.setEnabled(true);
        txtCantidadEjes.setEnabled(true);
        txtCantidadRodadas.setEnabled(true);
        
        
        
    }

    
 
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    
    
    
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CategoriaButton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPrincipal = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        optCompacto = new javax.swing.JRadioButton();
        optLujo = new javax.swing.JRadioButton();
        optFurgoneta = new javax.swing.JRadioButton();
        optCamioneta = new javax.swing.JRadioButton();
        txtMarca = new javax.swing.JTextField();
        txtNumeroSerie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCantidadPasajeros = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCapacidadCarga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCantidadRodadas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCantidadEjes = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVerInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        listaPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));
        listaPrincipal.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jScrollPane1.setViewportView(listaPrincipal);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecciona la Categoria: ");

        comboCategoria.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Auto Compacto", "Auto de Lujo", "Furgoneta", "Camioneta" }));
        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rellena los siguientes datos para agregar un vehículo:");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        CategoriaButton.add(optCompacto);
        optCompacto.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        optCompacto.setForeground(new java.awt.Color(255, 255, 255));
        optCompacto.setText("Compacto");
        optCompacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCompactoActionPerformed(evt);
            }
        });

        CategoriaButton.add(optLujo);
        optLujo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        optLujo.setForeground(new java.awt.Color(255, 255, 255));
        optLujo.setText("Lujo");
        optLujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optLujoActionPerformed(evt);
            }
        });

        CategoriaButton.add(optFurgoneta);
        optFurgoneta.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        optFurgoneta.setForeground(new java.awt.Color(255, 255, 255));
        optFurgoneta.setText("Furgoneta");
        optFurgoneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optFurgonetaActionPerformed(evt);
            }
        });

        CategoriaButton.add(optCamioneta);
        optCamioneta.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        optCamioneta.setForeground(new java.awt.Color(255, 255, 255));
        optCamioneta.setText("Camioneta");
        optCamioneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCamionetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(optCamioneta)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(optLujo)
                        .addComponent(optCompacto)
                        .addComponent(optFurgoneta)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(optCompacto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optLujo)
                .addGap(18, 18, 18)
                .addComponent(optFurgoneta)
                .addGap(18, 18, 18)
                .addComponent(optCamioneta)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Marca:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NroSerieMotor:");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Año:");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio:");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cantidad Pasajeros:");

        txtCantidadPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadPasajerosActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Capacidad Carga (kgs):");

        txtCapacidadCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadCargaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cantidad Rodadas:");

        txtCantidadRodadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadRodadasActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cantidad Ejes:");

        txtCantidadEjes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadEjesActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnAgregar.setText("Agregar Vehículo");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton1.setText("Vaciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AGENCIA DE AUTOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(341, 341, 341))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        btnVerInfo.setBackground(new java.awt.Color(102, 102, 102));
        btnVerInfo.setText("Mas Información");
        btnVerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(31, 31, 31)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(txtPrecio)
                            .addComponent(txtNumeroSerie)
                            .addComponent(txtMarca)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnVerInfo)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidadPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCapacidadCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadRodadas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadEjes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(610, 610, 610)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnEliminar)
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCantidadPasajeros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtCapacidadCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(btnAgregar)
                                    .addComponent(btnVerInfo)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidadRodadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidadEjes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// .-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-..-
    
    
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
             String marca = txtMarca.getText();
            String numeroSerieMotor = txtNumeroSerie.getText();
            double precio = Double.parseDouble(txtPrecio.getText());
            int anio = Integer.parseInt(txtAnio.getText());
        
            //Para generalizar
            Auto auto;
            
            
            
                 //Dependiendo del RadioButton seleccionado
            
               if (optCompacto.isSelected()){
               int cantPasajerosCompacto = Integer.parseInt( txtCantidadPasajeros.getText());
               auto= new AutoCompacto ( marca , numeroSerieMotor , precio , anio ,cantPasajerosCompacto);
                auto.setDescuento(precio);
                System.out.println(auto.toString());
                lista.add(auto);  
//                 setLista(lista);
//                cargarLista();                
            }
            
             
                if (optLujo.isSelected()){
                int cantPasajerosLujo = Integer.parseInt( txtCantidadPasajeros.getText());    
                auto = new AutoLujo ( marca , numeroSerieMotor , precio , anio ,cantPasajerosLujo);
                auto.setDescuento(precio);
                System.out.println(auto.toString());
                lista.add(auto);
//                  setLista(lista);
//                cargarLista();                 
                 
            }  

                if (optFurgoneta.isSelected()){
                int cantPasajerosFurgoneta = Integer.parseInt( txtCantidadPasajeros.getText());    
                auto= new Furgoneta ( marca , numeroSerieMotor , precio , anio ,cantPasajerosFurgoneta);
                auto.setDescuento(precio);
                System.out.println(auto.toString());
                lista.add(auto);
//                 setLista(lista);
//                cargarLista();          
            }
               
                if (optCamioneta.isSelected()){
                int cantEjes = Integer.parseInt( txtCantidadEjes.getText());    
                float capacidadCargaKgs = Float.parseFloat(txtCapacidadCarga.getText());
                int cantidadEjes = Integer.parseInt(txtCantidadEjes.getText());
                int cantidadRodadas = Integer.parseInt(txtCantidadRodadas.getText());                
                auto = new Camioneta ( marca , numeroSerieMotor , precio , anio , capacidadCargaKgs, cantidadEjes, cantidadRodadas );
                auto.setDescuento(precio);
                System.out.println(auto.toString());
                 lista.add(auto);
//                setLista(lista);
//                cargarLista(); 
            }
                listaModelo.clear();
               setLista(lista);
                cargarLista(); 

                
                
                
            
    }//GEN-LAST:event_btnAgregarActionPerformed

    
    
    
    
    private void optCompactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCompactoActionPerformed
        txtCantidadPasajeros.setEnabled(true);
        txtCapacidadCarga.setEnabled(false);
        txtCantidadEjes.setEnabled(false);
        txtCantidadRodadas.setEnabled(false);
    }//GEN-LAST:event_optCompactoActionPerformed

    private void optLujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optLujoActionPerformed
        txtCantidadPasajeros.setEnabled(true);
        txtCapacidadCarga.setEnabled(false);
        txtCantidadEjes.setEnabled(false);
        txtCantidadRodadas.setEnabled(false);
    }//GEN-LAST:event_optLujoActionPerformed

    private void optFurgonetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optFurgonetaActionPerformed
        txtCantidadPasajeros.setEnabled(true);
        txtCapacidadCarga.setEnabled(false);
        txtCantidadEjes.setEnabled(false);
        txtCantidadRodadas.setEnabled(false);
    }//GEN-LAST:event_optFurgonetaActionPerformed

    private void optCamionetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCamionetaActionPerformed
        txtCantidadPasajeros.setEnabled(false);
        txtCapacidadCarga.setEnabled(true);
        txtCantidadEjes.setEnabled(true);
        txtCantidadRodadas.setEnabled(true);
    }//GEN-LAST:event_optCamionetaActionPerformed

    
    //Metodo para eliminar Fila seleccinada ..............................................
    private void eliminarItemSeleccionado() {
    int indiceSeleccionado = listaPrincipal.getSelectedIndex();
    if (indiceSeleccionado != -1) {  // Verifica que se haya seleccionado un elemento
        DefaultListModel<String> modeloLista = (DefaultListModel<String>) listaPrincipal.getModel();
        modeloLista.removeElementAt(indiceSeleccionado);
    }
}
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       eliminarItemSeleccionado();
    }//GEN-LAST:event_btnEliminarActionPerformed

    
    //-------------------------------------------------------------------------------------
    
    
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
          
        String criterio = txtBuscar.getText();
        DefaultListModel<String> modeloResultado = new DefaultListModel<>();

        for (int i = 0; i < listaModelo.size(); i++) {
            String elemento = listaModelo.getElementAt(i).toString();
            if (elemento.contains(criterio)) {
                modeloResultado.addElement(elemento);
            }
        }

        listaPrincipal.setModel(modeloResultado);
     
     
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void comboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaActionPerformed
        
        
                String categoriaSeleccionada = (String) comboCategoria.getSelectedItem();
        DefaultListModel<String> modeloFiltrado = new DefaultListModel<>();

        if (categoriaSeleccionada.equals("Todos")) {
     
            listaPrincipal.setModel(listaModelo);
        } else {
  
            for (int i = 0; i < listaModelo.size(); i++) {
                String elemento = listaModelo.getElementAt(i).toString();
  
                if (elemento.startsWith(categoriaSeleccionada)) {
                    modeloFiltrado.addElement(elemento);
                }
            }

            listaPrincipal.setModel(modeloFiltrado);
        }
        
        //.........................................................
        
  
        
        
        
        
        
    }//GEN-LAST:event_comboCategoriaActionPerformed

    private void txtCantidadRodadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadRodadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadRodadasActionPerformed

    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtMarca.setText("");
        txtNumeroSerie.setText("");
        txtAnio.setText("");
        txtPrecio.setText("");
        txtCantidadPasajeros.setText("");
        txtCantidadRodadas.setText("");
        txtCapacidadCarga.setText("");
        txtCantidadEjes.setText("");
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCantidadPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadPasajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadPasajerosActionPerformed

    private void txtCantidadEjesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadEjesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadEjesActionPerformed

    private void txtCapacidadCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadCargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadCargaActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // VER INFORMACION EXTRA
    private void btnVerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerInfoActionPerformed
        FrameInformacion newFrameInformacion = new FrameInformacion ();
        
        newFrameInformacion.setVisible(true);
    }//GEN-LAST:event_btnVerInfoActionPerformed
 
    
    
    
 
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup CategoriaButton;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVerInfo;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaPrincipal;
    private javax.swing.JRadioButton optCamioneta;
    private javax.swing.JRadioButton optCompacto;
    private javax.swing.JRadioButton optFurgoneta;
    private javax.swing.JRadioButton optLujo;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidadEjes;
    private javax.swing.JTextField txtCantidadPasajeros;
    private javax.swing.JTextField txtCantidadRodadas;
    private javax.swing.JTextField txtCapacidadCarga;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNumeroSerie;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
